# Generated by Django 5.1.5 on 2025-11-20 15:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('lname', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('designation', models.TextField(blank=True, null=True)),
                ('qualification', models.TextField(blank=True, null=True)),
                ('desciption', models.TextField(blank=True, null=True)),
                ('pass_text', models.TextField(blank=True, null=True)),
                ('privilages', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('activefrom', models.DateField(blank=True, null=True)),
                ('activeto', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='users')),
                ('idproof', models.FileField(blank=True, null=True, upload_to='idproof')),
                ('user_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'superadmin'), (2, 'counsellor'), (3, 'teacher'), (4, 'student')], default=1, null=True)),
                ('fcm', models.TextField(blank=True, null=True)),
                ('mytoken', models.TextField(blank=True, null=True)),
                ('uniqueid', models.IntegerField(blank=True, default=0, null=True)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_premium', models.BooleanField(blank=True, default=False, null=True)),
                ('is_install', models.BooleanField(blank=True, default=False, null=True)),
                ('is_noti_5', models.BooleanField(blank=True, default=False, null=True)),
                ('is_noti_3', models.BooleanField(blank=True, default=False, null=True)),
                ('is_insta_5', models.BooleanField(blank=True, default=False, null=True)),
                ('is_insta_3', models.BooleanField(blank=True, default=False, null=True)),
                ('is_insta_10', models.BooleanField(blank=True, default=False, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('admin', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
