# Generated by Django 5.1.5 on 2025-11-20 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='activefrom',
        ),
        migrations.RemoveField(
            model_name='user',
            name='activeto',
        ),
        migrations.RemoveField(
            model_name='user',
            name='desciption',
        ),
        migrations.RemoveField(
            model_name='user',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='user',
            name='exam_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='idproof',
        ),
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_insta_10',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_insta_3',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_insta_5',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_install',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_noti_3',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_noti_5',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_premium',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mytoken',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pass_text',
        ),
        migrations.RemoveField(
            model_name='user',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='user',
            name='uniqueid',
        ),
    ]
