# Generated by Django 5.1.5 on 2025-11-20 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_remove_user_activefrom_remove_user_activeto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='admin',
        ),
    ]
