# Generated by Django 5.1.5 on 2025-11-20 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_remove_user_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='privilages',
        ),
    ]
