# Generated by Django 5.1.5 on 2025-11-20 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0007_alter_category_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='superadmin.category'),
        ),
    ]
